spring:
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@127.0.0.1:1521:db11g
    username: che
    password: 1425329
logging.level:
  # jdbc.sqltiming: FATAL
  jdbc.connection: FATAL
  jdbc.sqlonly: FATAL
  jdbc.audit: FATAL
  jdbc.resultset: FATAL
  jdbc.resultsettable: FATAL